### PR TITLE
express love for cookies

### PR DESCRIPTION
**Pull request by dmo-tf**
i wish to express my love for cookies, so here it is!

### CODE REVIEW

**Comment by dmo-tf** [comment]
Im not sure we should mention cookies.

**Comment by TeflonDon94** [comment]
But cookies are awesome!!!! <3

**Comment by dmo-tf** [comment]
You know what, you're totally right.

**Comment by TeflonDon94** [comment]
Come to think of it, mabe we should get milk as well before we enter cookies!

**Pull request merged**
